name: Java CI with Maven and Allure Report

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run tests with Maven
        run: mvn -Dtest=ApiTestRunner test

      - name: Generate Allure report
        run: mvn allure:report

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/allure-maven-plugin

